Product.create!([
  {name: "Nidoking", price: "252.0", image_url: "", description: "Verdanturf Town", stock: nil},
  {name: "Meowth", price: "188.0", image_url: "", description: "Frontier Access", stock: nil},
  {name: "Staryu", price: "741.0", image_url: "", description: "Opelucid City", stock: nil},
  {name: "Primeape", price: "276.0", image_url: "", description: "Dendemille Town", stock: nil},
  {name: "Arcanine", price: "428.0", image_url: "", description: "One Island", stock: nil},
  {name: "Gloom", price: "668.0", image_url: "", description: "Cianwood City", stock: nil},
  {name: "Golem", price: "663.0", image_url: "", description: "Blackthorn City", stock: nil},
  {name: "Kakuna", price: "916.0", image_url: "", description: "Solaceon Town", stock: nil},
  {name: "Jynx", price: "783.0", image_url: "", description: "Virbank City", stock: nil},
  {name: "Victreebel", price: "690.0", image_url: "", description: "Icirrus City", stock: nil},
  {name: "Rhydon", price: "805.0", image_url: "", description: "Solaceon Town", stock: nil},
  {name: "Persian", price: "463.0", image_url: "", description: "Ecruteak City", stock: nil},
  {name: "Poliwrath", price: "574.0", image_url: "", description: "Sunyshore City", stock: nil},
  {name: "Clefairy", price: "951.0", image_url: "", description: "Rustboro City", stock: nil},
  {name: "Jynx", price: "896.0", image_url: "", description: "Rustboro City", stock: nil},
  {name: "Farfetch'd", price: "815.0", image_url: "", description: "Twinleaf Town", stock: nil},
  {name: "Weedle", price: "753.0", image_url: "", description: "Ambrette Town", stock: nil},
  {name: "Vulpix", price: "781.0", image_url: "", description: "Verdanturf Town", stock: nil},
  {name: "Rhyhorn", price: "345.0", image_url: "", description: "Eterna City", stock: nil},
  {name: "Poliwag", price: "279.0", image_url: "", description: "Ever Grande City", stock: nil},
  {name: "Poliwag", price: "819.0", image_url: "", description: "Mossdeep City", stock: nil},
  {name: "Clefairy", price: "926.0", image_url: "", description: "Sunyshore City", stock: nil},
  {name: "Magnemite", price: "900.0", image_url: "", description: "Canalave City", stock: nil},
  {name: "Cubone", price: "401.0", image_url: "", description: "Six Island", stock: nil},
  {name: "Alakazam", price: "795.0", image_url: "", description: "Verdanturf Town", stock: nil},
  {name: "Gyarados", price: "909.0", image_url: "", description: "Laverre City", stock: nil},
  {name: "Machop", price: "145.0", image_url: "", description: "Mahogany Town", stock: nil},
  {name: "Beedrill", price: "194.0", image_url: "", description: "Petalburg City", stock: nil},
  {name: "Butterfree", price: "467.0", image_url: "", description: "Eterna City", stock: nil},
  {name: "Mew", price: "608.0", image_url: "", description: "Nuvema Town", stock: nil},
  {name: "Dragonair", price: "227.0", image_url: "", description: "Saffron City", stock: nil},
  {name: "Pikachu", price: "166.0", image_url: "", description: "Pallet Town", stock: nil},
  {name: "Rhyhorn", price: "319.0", image_url: "", description: "Cianwood City", stock: nil},
  {name: "Magnemite", price: "767.0", image_url: "", description: "Vermilion City", stock: nil},
  {name: "Kakuna", price: "648.0", image_url: "", description: "Undella Town", stock: nil},
  {name: "Mr. Mime", price: "196.0", image_url: "", description: "Survival Area", stock: nil},
  {name: "Charmeleon", price: "133.0", image_url: "", description: "Aquacorde Town", stock: nil},
  {name: "Rattata", price: "925.0", image_url: "", description: "Lumiose City", stock: nil},
  {name: "Bellsprout", price: "892.0", image_url: "", description: "Nacrene City", stock: nil},
  {name: "Dugtrio", price: "168.0", image_url: "", description: "Striaton City", stock: nil},
  {name: "Nidoking", price: "616.0", image_url: "", description: "Goldenrod City", stock: nil},
  {name: "Dodrio", price: "353.0", image_url: "", description: "Sootopolis City", stock: nil},
  {name: "Exeggcute", price: "336.0", image_url: "", description: "Six Island", stock: nil},
  {name: "Primeape", price: "196.0", image_url: "", description: "Jubilife City", stock: nil},
  {name: "Jolteon", price: "717.0", image_url: "", description: "Lumiose City", stock: nil},
  {name: "Aerodactyl", price: "945.0", image_url: "", description: "Aspertia City", stock: nil},
  {name: "Pidgeot", price: "779.0", image_url: "", description: "Solaceon Town", stock: nil},
  {name: "Chansey", price: "872.0", image_url: "", description: "Ambrette Town", stock: nil},
  {name: "Beedrill", price: "374.0", image_url: "", description: "Castelia City", stock: nil},
  {name: "Marowak", price: "625.0", image_url: "", description: "Humilau City", stock: nil},
  {name: "Dratini", price: "543.0", image_url: "", description: "Lacunosa Town", stock: nil},
  {name: "Shellder", price: "779.0", image_url: "", description: "Floccesy Town", stock: nil},
  {name: "apple", price: "60.0", image_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3ARed_Apple.jpg&psig=AOvVaw2yeteYUvnCj5K0cxGXkSYL&ust=1670528155395000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCPjnk7yg6PsCFQAAAAAdAAAAABAE", description: "delicious fruit from a tree", stock: nil},
  {name: "test", price: "0.0", image_url: "test", description: "test", stock: nil}
])
