### PRODUCT INDEX
GET http://localhost:3000/products.json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzEyMTQ3Mjl9.fVXo-nulpQMKvIRlKZN8IkkVXukVLX-0HadbnFoy5MI"


### PRODUCT SHOW
GET http://localhost:3000/products/5.json

### PRODUCT CREATE
POST http://localhost:3000/products.json 
Content-type: application/json

{
  "name": "water bowl",
  "price": "10",
  "image_url": "",
  "description": "a bowl used for drinking",
  "stock": "14"
}

### PRODUCT UPDATE
PATCH http://localhost:3000/products/1.json
Content-type: application/json 

{
"name": "",
"price": "",
"image_url": "https://media.istockphoto.com/id/1285221381/photo/a-bowl-of-water.jpg?b=1&s=170667a&w=0&k=20&c=TbJ5MdcHvKY6HpTBLJt3HbZy0ZH2DDDFeuOYhJ_dyhU=",
"description": ""
}

### PRODUCT DELETE
DELETE http://localhost:3000/products/55.json



### SUPPLIER INDEX
http://localhost:3000/supplier

### SUPPLIER SHOW
http://localhost:3000/supplier/2






# #### IMAGE INDEX
# GET http://localhost:3000/images.json

# ### IMAGE SHOW
# GET http://localhost:3000/images/1.json

# ### IMAGE CREATE
# POST http://localhost:3000/images/1.json
# Content-Type: application/json

# {
#   "url": "https://media.istockphoto.com/id/1285221381/photo/a-bowl-of-water.jpg?b=1&s=170667a&w=0&k=20&c=TbJ5MdcHvKY6HpTBLJt3HbZy0ZH2DDDFeuOYhJ_dyhU="
# }



### USER CREATE
POST http://localhost:3000/users.json 
Content-Type: application/json

{
  "name": "Ryan",
  "email": "Ryan@test.com",
  "password": "password"
}
### USER LOG IN
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}


### CREATE ORDER
POST http://localhost:3000/orders.json 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzE1Njc4NDd9.lyJmJflYyVrlKp9tD8MWTSAjBtNB2MXXwErs-99MLyY 

{
  "product_id": "24",
  "quantity": "2"
}

### SHOW ORDER
GET http://localhost:3000/orders/1.json

### INDEX ORDER
GET http://localhost:3000.orders.json 


### Carted Product CREATE
POST http://localhost:3000/carted_product.json 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzE2NDUxMjB9.dk1fTuSL6p-zxZrnidVOCC6Nfr96ejnbrvBU3ik7usw

{
  "product_id": "5",
  "quantity": "3"
}

### CARTED PRODUCT INDEX
GET http://localhost:3000/carted_product.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzE2NDUxMjB9.dk1fTuSL6p-zxZrnidVOCC6Nfr96ejnbrvBU3ik7usw