### 
GET http://localhost:3000/products.json 

### 
GET http://localhost:3000/products/1.json 

###
POST http://localhost:3000/products.json 
Content-type: application/json

{
  "name": "water bowl",
  "price": "10",
  "image_url": "",
  "description": "delicious fruit from a tree",
  "stock": "14"
}

###
PATCH http://localhost:3000/products/1.json
Content-type: application/json 

{
"name": "",
"price": "",
"image_url": "https://media.izi.travel/4e9d2b2c-83c3-4a84-8675-7cc276270305/5f063515-609a-4507-92bb-59fdd15b521b_800x600.jpg",
"description": ""
}

###
DELETE http://localhost:3000/products/55.json